version: 2.1

workflows:
  ci:
    jobs:
      - back

jobs:
  back:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    resource_class: large
    working_directory: ~/phoenix_gerlessver
    steps:
      - checkout
      - run:
          name: Build
          command: |
            ARG_USER_UID=$(id -u) ARG_USER_GID=$(id -g) docker compose config
            ARG_USER_UID=$(id -u) ARG_USER_GID=$(id -g) docker compose build
      - restore_cache:
          name: Restore Cache
          key: '{{ checksum "mix.lock" }}'
      - run:
          name: Up
          command: docker compose up -d
      - run:
          name: Dependencies
          command: |
            docker compose exec app mix local.hex --force
            docker compose exec app mix local.rebar --force
            docker compose exec app mix deps.get
            docker compose exec app mix deps.compile
      - run:
          name: NPM 
          command: docker compose exec app npm install
      - run:
          name: Database
          command: docker compose exec app mix ecto.create
      - save_cache:
          name: Save Cache
          key: deps-{{ checksum "mix.lock" }}
          paths:
            - deps
            - _build
      - run:
          name: Tests
          command: docker compose exec app mix test